'use strict';

/**
 * @ngdoc service
 * @name blogApp.emotis
 * @description
 * # emotis
 * Service in the blogApp.
 */
angular.module('blogApp')
  .factory('Emotis', function () {
    // AngularJS will instantiate a singleton by calling "new" on this function
    // var emotis = [
    // 	{content:':smile:'},
    // 	{content:':laughing:'},
    // 	{content:':blush:'},
    // 	{content:':smiley:'},
    // 	{content:':relaxed:'},
    // 	{content:':smirk:'},
    // 	{content:':heart_eyes:'},
    // 	{content:':kissing_heart:'},
    // 	{content:':kissing_closed_eyes:'},
    // 	{content:':flushed:'},
    // 	{content:':relieved:'},
    // 	{content:':grin:'},
    // 	{content:':wink:'},
    // 	{content:':stuck_out_tongue_winking_eye:'},
    // 	{content:':sleeping:'},
    // 	{content:':worried:'},
    // 	{content:':frowning:'},
    // 	{content:':open_mouth:'},
    // 	{content:':confused:'},
    // 	{content:':unamused:'},
    // 	{content:':sweat_smile:'},
    // 	{content:':sweat:'},
    // 	{content:':disappointed_relieved:'},
    // 	{content:':pensive:'},
    // 	{content:':cold_sweat:'},
    // 	{content:':cry:'},
    // 	{content:':sob:'},
    // 	{content:':joy:'},
    // 	{content:':scream:'},
    // 	{content:':rage:'},
    // 	{content:':neckbeard:'},
    // 	{content:':triumph:'},
    // 	{content:':yum:'},
    // 	{content:':sunglasses:'},
    // 	{content:':smiling_imp:'},
    // 	{content:':innocent:'},
    // 	{content:':heart:'},
    // 	{content:':broken_heart:'},
    // 	{content:':shit:'},
    // 	{content:':+1:'},
    // 	{content:':-1:'},
    // 	{content:':v:'},
    // 	{content:':raised_hands:'},
    // 	{content:':clap:'},
    // 	{content:':metal:'},
    // 	{content:':fu:'},
    // 	{content:':dancers:'},
    // 	{content:':couplekiss:'},
    // 	{content:':japanese_ogre:'},
    // 	{content:':japanese_goblin:'},
    // 	{content:':see_no_evil:'},
    // 	{content:':hear_no_evil:'},
    // 	{content:':speak_no_evil:'},
    // 	{content:':skull:'},
    // 	{content:':kiss:'},
    // 	{content:':ear:'},
    // 	{content:':eyes:'},
    // 	{content:':speech_balloon:'},
    // 	{content:':thought_balloon:'},
    // 	{content:':love_letter:'},
    // 	{content:':trollface:'},
    // 	{content:':boom:'},
    // 	{content:':rose:'},
    // 	{content:':four_leaf_clover:'},
    // 	{content:':gift_heart:'},
    // 	{content:':jack_o_lantern:'},
    // 	{content:':ghost:'},
    // 	{content:':santa:'},
    // 	{content:':christmas_tree:'},
    // 	{content:':gift:'},
    // 	{content:':tada:'},
    // 	{content:':phone:'},
    // 	{content:':mushroom:'},
    // 	{content:':computer:'},
    // 	{content:':crystal_ball:'},
    // 	{content:':cd:'},
    // 	{content:':tv:'},
    // 	{content:':vhs:'},
    // 	{content:':alarm_clock:'},
    // 	{content:':watch:'},
    // 	{content:':radio:'},
    // 	{content:':bath:'},
    // 	{content:':mailbox:'},
    // 	{content:':toilet:'},
    // 	{content:':hammer:'},
    // 	{content:':moneybag:'},
    // 	{content:':credit_card:'},
    // 	{content:':money_with_wings:'},
    // 	{content:':postal_horn:'},
    // 	{content:':tophat:'},
    // 	{content:':smoking:'},
    // 	{content:':pill:'},
    // 	{content:':syringe:'},
    // 	{content:':scissors:'},
    // 	{content:':soccer:'},
    // 	{content:':basketball:'},
    // 	{content:':snowboarder:'},
    // 	{content:':swimmer:'},
    // 	{content:':surfer:'},
    // 	{content:':trophy:'},
    // 	{content:':space_invader:'},
    // 	{content:':dart:'},
    // 	{content:':video_game:'},
    // 	{content:':microphone:'},
    // 	{content:':headphones:'},
    // 	{content:':lipstick:'},
    // 	{content:':necktie:'},
    // 	{content:':bikini:'},
    // 	{content:':mega:'},
    // 	{content:':hourglass:'},
    // 	{content:':mag:'},
    // 	{content:':date:'},
    // 	{content:':art:'},
    // 	{content:':crown:'},
    // 	{content:':banana:'},
    // 	{content:':beers:'},
    // 	{content:':coffee:'},
    // 	{content:':wine_glass:'},
    // 	{content:':birthday:'},
    // 	{content:':atm:'}

    // ];

    var people = [
        {content:':bowtie:'},
        {content:':smile:'},
        {content:':laughing:'},
        {content:':blush:'},
        {content:':smiley:'},
        {content:':relaxed:'},
        {content:':smirk:'},
        {content:':heart_eyes:'},
        {content:':kissing_heart:'},
        {content:':kissing_closed_eyes:'},
        {content:':flushed:'},
        {content:':relieved:'},
        {content:':grin:'},
        {content:':wink:'},
        {content:':stuck_out_tongue_winking_eye:'},
        {content:':stuck_out_tongue_closed_eyes:'},
        {content:':grinning:'},
        {content:':kissing:'},
        {content:':kissing_smiling_eyes:'},
        {content:':stuck_out_tongue:'},
        {content:':sleeping:'},
        {content:':worried:'},
        {content:':frowning:'},
        {content:':anguished:'},
        {content:':open_mouth:'},
        {content:':grimacing:'},
        {content:':confused:'},
        {content:':hushed:'},
        {content:':expressionless:'},
        {content:':unamused:'},
        {content:':sweat_smile:'},
        {content:':sweat:'},
        {content:':disappointed_relieved:'},
        {content:':weary:'},
        {content:':pensive:'},
        {content:':disappointed:'},
        {content:':confounded:'},
        {content:':fearful:'},
        {content:':cold_sweat:'},
        {content:':persevere:'},
        {content:':cry:'},
        {content:':sob:'},
        {content:':joy:'},
        {content:':astonished:'},
        {content:':scream:'},
        {content:':neckbeard:'},
        {content:':tired_face:'},
        {content:':angry:'},
        {content:':rage:'},
        {content:':triumph:'},
        {content:':sleepy:'},
        {content:':yum:'},
        {content:':mask:'},
        {content:':sunglasses:'},
        {content:':dizzy_face:'},
        {content:':imp:'},
        {content:':smiling_imp:'},
        {content:':neutral_face:'},
        {content:':no_mouth:'},
        {content:':innocent:'},
        {content:':alien:'},
        {content:':yellow_heart:'},
        {content:':blue_heart:'},
        {content:':purple_heart:'},
        {content:':heart:'},
        {content:':green_heart:'},
        {content:':broken_heart:'},
        {content:':heartbeat:'},
        {content:':heartpulse:'},
        {content:':two_hearts:'},
        {content:':revolving_hearts:'},
        {content:':cupid:'},
        {content:':sparkling_heart:'},
        {content:':sparkles:'},
        {content:':star:'},
        {content:':star2:'},
        {content:':dizzy:'},
        {content:':boom:'},
        {content:':anger:'},
        {content:':exclamation:'},
        {content:':question:'},
        {content:':grey_exclamation:'},
        {content:':grey_question:'},
        {content:':zzz:'},
        {content:':dash:'},
        {content:':sweat_drops:'},
        {content:':notes:'},
        {content:':musical_note:'},
        {content:':fire:'},
        {content:':shit:'},
        {content:':+1:'},
        {content:':-1:'},
        {content:':ok_hand:'},
        {content:':punch:'},
        {content:':fist:'},
        {content:':v:'},
        {content:':wave:'},
        {content:':hand:'},
        {content:':open_hands:'},
        {content:':point_up:'},
        {content:':point_down:'},
        {content:':point_left:'},
        {content:':point_right:'},
        {content:':raised_hands:'},
        {content:':pray:'},
        {content:':point_up_2:'},
        {content:':clap:'},
        {content:':muscle:'},
        {content:':metal:'},
        {content:':fu:'},
        {content:':runner:'},
        {content:':couple:'},
        {content:':family:'},
        {content:':two_men_holding_hands:'},
        {content:':two_women_holding_hands:'},
        {content:':dancer:'},
        {content:':dancers:'},
        {content:':ok_woman:'},
        {content:':no_good:'},
        {content:':information_desk_person:'},
        {content:':raising_hand:'},
        {content:':bride_with_veil:'},
        {content:':person_with_pouting_face:'},
        {content:':person_frowning:'},
        {content:':bow:'},
        {content:':couplekiss:'},
        {content:':couple_with_heart:'},
        {content:':massage:'},
        {content:':haircut:'},
        {content:':nail_care:'},
        {content:':boy:'},
        {content:':girl:'},
        {content:':woman:'},
        {content:':man:'},
        {content:':baby:'},
        {content:':older_woman:'},
        {content:':older_man:'},
        {content:':person_with_blond_hair:'},
        {content:':man_with_gua_pi_mao:'},
        {content:':man_with_turban:'},
        {content:':construction_worker:'},
        {content:':cop:'},
        {content:':angel:'},
        {content:':princess:'},
        // {content:':smiley_cat:'},
        {content:':smile_cat:'},
        {content:':heart_eyes_cat:'},
        {content:':kissing_cat:'},
        {content:':smirk_cat:'},
        {content:':scream_cat:'},
        {content:':crying_cat_face:'},
        {content:':joy_cat:'},
        {content:':pouting_cat:'},
        {content:':japanese_ogre:'},
        {content:':japanese_goblin:'},
        {content:':see_no_evil:'},
        {content:':hear_no_evil:'},
        {content:':speak_no_evil:'},
        {content:':guardsman:'},
        {content:':skull:'},
        {content:':feet:'},
        {content:':lips:'},
        {content:':kiss:'},
        {content:':droplet:'},
        {content:':ear:'},
        {content:':eyes:'},
        {content:':nose:'},
        {content:':tongue:'},
        {content:':love_letter:'},
        {content:':bust_in_silhouette:'},
        {content:':busts_in_silhouette:'},
        {content:':speech_balloon:'},
        {content:':thought_balloon:'},
        {content:':feelsgood:'},
        {content:':finnadie:'},
        {content:':goberserk:'},
        {content:':godmode:'},
        {content:':hurtrealbad:'},
        {content:':rage1:'},
        {content:':rage2:'},
        {content:':rage3:'},
        {content:':rage4:'},
        {content:':suspect:'},
        {content:':trollface:'}
        ];

    var nature = [
        {content:':sunny:'},
        {content:':umbrella:'},
        {content:':cloud:'},
        {content:':snowflake:'},
        {content:':snowman:'},
        {content:':zap:'},
        {content:':cyclone:'},
        {content:':foggy:'},
        {content:':ocean:'},
        {content:':cat:'},
        {content:':dog:'},
        {content:':mouse:'},
        {content:':hamster:'},
        {content:':rabbit:'},
        {content:':wolf:'},
        {content:':frog:'},
        {content:':tiger:'},
        {content:':koala:'},
        {content:':bear:'},
        {content:':pig:'},
        {content:':pig_nose:'},
        {content:':cow:'},
        {content:':boar:'},
        {content:':monkey_face:'},
        {content:':monkey:'},
        {content:':horse:'},
        {content:':racehorse:'},
        {content:':camel:'},
        {content:':sheep:'},
        {content:':elephant:'},
        {content:':panda_face:'},
        {content:':snake:'},
        {content:':bird:'},
        {content:':baby_chick:'},
        {content:':hatched_chick:'},
        {content:':hatching_chick:'},
        {content:':chicken:'},
        {content:':penguin:'},
        {content:':turtle:'},
        {content:':bug:'},
        {content:':honeybee:'},
        {content:':ant:'},
        {content:':beetle:'},
        {content:':snail:'},
        {content:':octopus:'},
        {content:':tropical_fish:'},
        {content:':fish:'},
        {content:':whale:'},
        {content:':whale2:'},
        {content:':dolphin:'},
        {content:':cow2:'},
        {content:':ram:'},
        {content:':rat:'},
        {content:':water_buffalo:'},
        {content:':tiger2:'},
        {content:':rabbit2:'},
        {content:':dragon:'},
        {content:':goat:'},
        {content:':rooster:'},
        {content:':dog2:'},
        {content:':pig2:'},
        {content:':mouse2:'},
        {content:':ox:'},
        {content:':dragon_face:'},
        {content:':blowfish:'},
        {content:':crocodile:'},
        {content:':dromedary_camel:'},
        {content:':leopard:'},
        {content:':cat2:'},
        {content:':poodle:'},
        {content:':paw_prints:'},
        {content:':bouquet:'},
        {content:':cherry_blossom:'},
        {content:':tulip:'},
        {content:':four_leaf_clover:'},
        {content:':rose:'},
        {content:':sunflower:'},
        {content:':hibiscus:'},
        {content:':maple_leaf:'},
        {content:':leaves:'},
        {content:':fallen_leaf:'},
        {content:':herb:'},
        {content:':mushroom:'},
        {content:':cactus:'},
        {content:':palm_tree:'},
        {content:':evergreen_tree:'},
        {content:':deciduous_tree:'},
        {content:':chestnut:'},
        {content:':seedling:'},
        {content:':blossom:'},
        {content:':ear_of_rice:'},
        {content:':shell:'},
        {content:':globe_with_meridians:'},
        {content:':sun_with_face:'},
        {content:':full_moon_with_face:'},
        {content:':new_moon_with_face:'},
        {content:':new_moon:'},
        {content:':waxing_crescent_moon:'},
        {content:':first_quarter_moon:'},
        {content:':waxing_gibbous_moon:'},
        {content:':full_moon:'},
        {content:':waning_gibbous_moon:'},
        {content:':first_quarter_moon:'},
        {content:':last_quarter_moon_with_face:'},
        {content:':first_quarter_moon_with_face:'},
        {content:':earth_africa:'},
        {content:':earth_americas:'},
        {content:':earth_asia:'},
        {content:':volcano:'},
        {content:':milky_way:'},
        {content:':partly_sunny:'},
        {content:':octocat:'},
        {content:':squirrel:'}
        ];

        var objects = [
        {content:':bamboo:'},
        {content:':gift_heart:'},
        {content:':dolls:'},
        {content:':school_satchel:'},
        {content:':mortar_board:'},
        {content:':flags:'},
        {content:':fireworks:'},
        {content:':sparkler:'},
        {content:':wind_chime:'},
        {content:':rice_scene:'},
        {content:':jack_o_lantern:'},
        {content:':ghost:'},
        {content:':santa:'},
        {content:':christmas_tree:'},
        {content:':gift:'},
        {content:':bell:'},
        {content:':no_bell:'},
        {content:':tanabata_tree:'},
        {content:':tada:'},
        {content:':confetti_ball:'},
        {content:':balloon:'},
        {content:':crystal_ball:'},
        {content:':cd:'},
        {content:':dvd:'},
        {content:':floppy_disk:'},
        {content:':camera:'},
        {content:':video_camera:'},
        {content:':movie_camera:'},
        {content:':computer:'},
        {content:':tv:'},
        {content:':iphone:'},
        {content:':phone:'},
        {content:':telephone_receiver:'},
        {content:':pager:'},
        {content:':fax:'},
        {content:':minidisc:'},
        {content:':vhs:'},
        {content:':sound:'},
        {content:':speaker:'},
        {content:':alarm_clock:'},
        {content:':watch:'},
        {content:':radio:'},
        {content:':satellite:'},
        {content:':loop:'},
        {content:':mag:'},
        {content:':mag_right:'},
        {content:':unlock:'},
        {content:':lock:'},
        {content:':lock_with_ink_pen:'},
        {content:':closed_lock_with_key:'},
        {content:':key:'},
        {content:':bulb:'},
        {content:':flashlight:'},
        {content:':high_brightness:'},
        {content:':low_brightness:'},
        {content:':electric_plug:'},
        {content:':battery:'},
        {content:':calling:'},
        {content:':email:'},
        {content:':mailbox:'},
        {content:':postbox:'},
        {content:':bath:'},
        {content:':bathtub:'},
        {content:':shower:'},
        {content:':toilet:'},
        {content:':wrench:'},
        {content:':nut_and_bolt:'},
        {content:':hammer:'},
        {content:':seat:'},
        {content:':moneybag:'},
        {content:':yen:'},
        {content:':dollar:'},
        {content:':pound:'},
        {content:':euro:'},
        {content:':credit_card:'},
        {content:':money_with_wings:'},
        {content:':e-mail:'},
        {content:':inbox_tray:'},
        {content:':outbox_tray:'},
        {content:':envelope:'},
        {content:':incoming_envelope:'},
        {content:':postal_horn:'},
        {content:':mailbox_closed:'},
        {content:':mailbox_with_mail:'},
        {content:':mailbox_with_no_mail:'},
        // {content:':package:'},   NO CARGA
        {content:':door:'},
        {content:':smoking:'},
        {content:':bomb:'},
        {content:':bomb:'},
        {content:':hocho:'},
        {content:':pill:'},
        {content:':syringe:'},
        {content:':page_facing_up:'},
        {content:':page_with_curl:'},
        {content:':bookmark_tabs:'},
        {content:':bar_chart:'},
        {content:':chart_with_upwards_trend:'},
        {content:':chart_with_downwards_trend:'},
        {content:':scroll:'},
        {content:':clipboard:'},
        {content:':calendar:'},
        {content:':date:'},
        {content:':card_index:'},
        {content:':file_folder:'},
        {content:':open_file_folder:'},
        {content:':scissors:'},
        {content:':pushpin:'},
        {content:':paperclip:'},
        {content:':black_nib:'},
        {content:':pencil2:'},
        {content:':straight_ruler:'},
        {content:':triangular_ruler:'},
        {content:':closed_book:'},
        {content:':green_book:'},
        {content:':blue_book:'},
        {content:':orange_book:'},
        {content:':notebook:'},
        {content:':notebook_with_decorative_cover:'},
        {content:':ledger:'},
        {content:':books:'},
        {content:':bookmark:'},
        {content:':name_badge:'},
        {content:':microscope:'},
        {content:':telescope:'},
        {content:':newspaper:'},
        {content:':football:'},
        {content:':basketball:'},
        {content:':soccer:'},
        {content:':baseball:'},
        {content:':tennis:'},
        {content:':8ball:'},
        {content:':rugby_football:'},
        {content:':bowling:'},
        {content:':golf:'},
        {content:':mountain_bicyclist:'},
        {content:':bicyclist:'},
        {content:':horse_racing:'},
        {content:':snowboarder:'},
        {content:':swimmer:'},
        {content:':surfer:'},
        {content:':ski:'},
        {content:':spades:'},
        {content:':hearts:'},
        {content:':clubs:'},
        {content:':diamonds:'},
        {content:':gem:'},
        {content:':ring:'},
        {content:':trophy:'},
        {content:':musical_score:'},
        {content:':musical_keyboard:'},
        {content:':violin:'},
        {content:':space_invader:'},
        {content:':video_game:'},
        {content:':black_joker:'},
        {content:':flower_playing_cards:'},
        {content:':game_die:'},
        {content:':dart:'},
        {content:':mahjong:'},
        {content:':clapper:'},
        {content:':memo:'},
        {content:':pencil:'},
        {content:':book:'},
        {content:':art:'},
        {content:':microphone:'},
        {content:':headphones:'},
        {content:':trumpet:'},
        {content:':saxophone:'},
        {content:':guitar:'},
        {content:':shoe:'},
        {content:':sandal:'},
        {content:':high_heel:'},
        {content:':lipstick:'},
        {content:':boot:'},
        {content:':shirt:'},
        {content:':necktie:'},
        {content:':womans_clothes:'},
        {content:':dress:'},
        {content:':running_shirt_with_sash:'},
        {content:':jeans:'},
        {content:':kimono:'},
        {content:':bikini:'},
        {content:':ribbon:'},
        {content:':tophat:'},
        {content:':crown:'},
        {content:':womans_hat:'},
        {content:':mans_shoe:'},
        {content:':closed_umbrella:'},
        {content:':briefcase:'},
        {content:':handbag:'},
        {content:':pouch:'},
        {content:':purse:'},
        {content:':eyeglasses:'},
        {content:':fishing_pole_and_fish:'},
        {content:':coffee:'},
        {content:':tea:'},
        {content:':sake:'},
        {content:':baby_bottle:'},
        {content:':beer:'},
        {content:':beers:'},
        {content:':cocktail:'},
        {content:':tropical_drink:'},
        {content:':wine_glass:'},
        {content:':fork_and_knife:'},
        {content:':pizza:'},
        {content:':hamburger:'},
        {content:':fries:'},
        {content:':poultry_leg:'},
        {content:':meat_on_bone:'},
        {content:':spaghetti:'},
        {content:':curry:'},
        {content:':fried_shrimp:'},
        {content:':bento:'},
        {content:':sushi:'},
        {content:':fish_cake:'},
        {content:':rice_ball:'},
        {content:':rice_cracker:'},
        {content:':rice:'},
        {content:':ramen:'},
        {content:':stew:'},
        {content:':oden:'},
        {content:':dango:'},
        {content:':egg:'},
        {content:':bread:'},
        {content:':doughnut:'},
        {content:':custard:'},
        {content:':icecream:'},
        {content:':ice_cream:'},
        {content:':shaved_ice:'},
        {content:':birthday:'},
        {content:':cake:'},
        {content:':cookie:'},
        {content:':chocolate_bar:'},
        {content:':candy:'},
        {content:':lollipop:'},
        {content:':honey_pot:'},
        {content:':apple:'},
        {content:':green_apple:'},
        {content:':tangerine:'},
        {content:':lemon:'},
        {content:':cherries:'},
        {content:':grapes:'},
        {content:':watermelon:'},
        {content:':strawberry:'},
        {content:':peach:'},
        {content:':melon:'},
        {content:':banana:'},
        {content:':pear:'},
        {content:':pineapple:'},
        {content:':sweet_potato:'},
        {content:':eggplant:'},
        {content:':tomato:'},
        {content:':corn:'}
        ];

    var places = [
        {content:':house:'},
        {content:':house_with_garden:'},
        {content:':school:'},
        {content:':office:'},
        {content:':post_office:'},
        {content:':hospital:'},
        {content:':bank:'},
        {content:':convenience_store:'},
        {content:':love_hotel:'},
        {content:':hotel:'},
        {content:':wedding:'},
        {content:':church:'},
        {content:':department_store:'},
        {content:':european_post_office:'},
        {content:':city_sunrise:'},
        {content:':city_sunset:'},
        {content:':japanese_castle:'},
        {content:':european_castle:'},
        {content:':tent:'},
        {content:':factory:'},
        {content:':tokyo_tower:'},
        {content:':japan:'},
        {content:':mount_fuji:'},
        {content:':sunrise_over_mountains:'},
        {content:':sunrise:'},
        {content:':stars:'},
        {content:':statue_of_liberty:'},
        {content:':bridge_at_night:'},
        {content:':carousel_horse:'},
        {content:':rainbow:'},
        {content:':ferris_wheel:'},
        {content:':fountain:'},
        {content:':roller_coaster:'},
        {content:':ship:'},
        {content:':speedboat:'},
        {content:':boat:'},
        {content:':sailboat:'},
        {content:':rowboat:'},
        {content:':anchor:'},
        {content:':rocket:'},
        {content:':airplane:'},
        {content:':helicopter:'},
        {content:':steam_locomotive:'},
        {content:':tram:'},
        {content:':mountain_railway:'},
        {content:':bike:'},
        {content:':aerial_tramway:'},
        {content:':suspension_railway:'},
        {content:':mountain_cableway:'},
        {content:':tractor:'},
        {content:':blue_car:'},
        {content:':oncoming_automobile:'},
        {content:':car:'},
        {content:':taxi:'},
        {content:':oncoming_taxi:'},
        {content:':articulated_lorry:'},
        {content:':bus:'},
        {content:':oncoming_bus:'},
        {content:':rotating_light:'},
        {content:':police_car:'},
        {content:':oncoming_police_car:'},
        {content:':fire_engine:'},
        {content:':ambulance:'},
        {content:':minibus:'},
        {content:':truck:'},
        {content:':train:'},
        {content:':station:'},
        {content:':train2:'},
        {content:':bullettrain_side:'},
        {content:':light_rail:'},
        {content:':monorail:'},
        {content:':railway_car:'},
        {content:':trolleybus:'},
        {content:':ticket:'},
        {content:':fuelpump:'},
        {content:':vertical_traffic_light:'},
        {content:':traffic_light:'},
        {content:':warning:'},
        {content:':construction:'},
        {content:':beginner:'},
        {content:':atm:'},
        {content:':slot_machine:'},
        {content:':busstop:'},
        {content:':barber:'},
        {content:':hotsprings:'},
        {content:':checkered_flag:'},
        {content:':crossed_flags:'},
        {content:':izakaya_lantern:'},
        {content:':moyai:'},
        {content:':circus_tent:'},
        {content:':performing_arts:'},
        {content:':round_pushpin:'},
        {content:':triangular_flag_on_post:'},
        {content:':jp:'},
        {content:':kr:'},
        {content:':cn:'},
        {content:':us:'},
        {content:':fr:'},
        {content:':es:'},
        {content:':it:'},
        {content:':ru:'},
        {content:':gb:'},
        {content:':uk:'},
        {content:':de:'}
        ];

        var allEmotis = people.concat(nature).concat(objects).concat(places);

    var Emotis = {
      all: allEmotis,
      get:function(){
      	return allEmotis;
        // return emotis;
      },
      getPeople:function(){
      	return people;
      },
      getNature:function(){
        return nature;
      },
      getObjects:function(){
        return objects;
      },
      getPlaces:function(){
        return places;
      }
  	};

  	return Emotis;
  });
